const Data = [
    {
      id: "1",
      title: "Poha",
      img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
      url: "abcd",
      username:"adnan khan",
      category: "Breakfast",
      likedcount:"4",
      likedby:"mallesh",
      commentedBy:"asas",
      comments:"asas",
      desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "2",
        title: "Poha",
        img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Travel",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "3",
        title: "Poha",
        img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Food",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "4",
        title: "Poha",
        img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Breakfast",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "5",
        title: "Poha",
        img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Breakfast",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "6",
        title: "Poha",
        img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Breakfast",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "7",
        title: "Poha",
        img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Breakfast",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },
    {
        id: "8",
        title: "Poha",
        img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
        url: "abcd",
        username:"adnan khan",
        category: "Breakfast",
        likedcount:"4",
        likedby:"mallesh",
        commentedBy:"asas",
        comments:"asas",
        desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
    },

  ];
   
  export default Data;