const Data = [
  {
    id: "1",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    date: "12 April 2023",
    title: "Poha",
    img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Travel", "Destination"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Non pulvinar neque laoreet suspendisse. Lectus nulla at volutpat diam ut venenatis tellus in. Turpis egestas sed tempus urna et pharetra. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Varius vel pharetra vel turpis nunc. Fringilla ut morbi tincidunt augue interdum velit euismod. Elit eget gravida cum sociis natoque penatibus et magnis. Habitant morbi tristique senectus et netus. Turpis massa tincidunt dui ut ornare lectus sit. Vestibulum morbi blandit cursus risus. Amet porttitor eget dolor morbi non arcu risus. Iaculis at erat pellentesque adipiscing commodo elit. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Tellus pellentesque eu tincidunt tortor aliquam. Sed vulputate mi sit amet mauris commodo. Id volutpat lacus laoreet non curabitur. Feugiat vivamus at augue eget arcu dictum varius duis at. Porta lorem mollis aliquam ut porttitor leo. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. Mi ipsum faucibus vitae aliquet nec. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. At consectetur lorem donec massa. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Sit amet consectetur adipiscing elit ut. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Amet mauris commodo quis imperdiet. Velit laoreet id donec ultrices tincidunt arcu non. Sed risus ultricies tristique nulla aliquet. Id interdum velit laoreet id donec ultrices. Nulla facilisi cras fermentum odio eu feugiat pretium. Amet consectetur adipiscing elit ut. Pharetra convallis posuere morbi leo urna molestie at. Senectus et netus et malesuada fames ac turpis egestas sed. Eget est lorem ipsum dolor sit amet consectetur adipiscing. Cras tincidunt lobortis feugiat vivamus. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Vivamus arcu felis bibendum ut tristique et egestas quis. Dolor sit amet consectetur adipiscing elit ut. Viverra justo nec ultrices dui sapien eget mi. Eu non diam phasellus vestibulum lorem sed. Nec feugiat in fermentum posuere urna nec. Leo a diam sollicitudin tempor id eu nisl nunc mi. Sed risus ultricies tristique nulla aliquet enim. Amet nisl suscipit adipiscing bibendum est. Lorem dolor sed viverra ipsum nunc aliquet. Diam sollicitudin tempor id eu. Nam at lectus urna duis convallis convallis tellus. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Mauris pharetra et ultrices neque ornare. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Dolor sit amet consectetur adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Gravida cum sociis natoque penatibus et. Vitae et leo duis ut diam quam. Viverra ipsum nunc aliquet bibendum enim.",
  },
  {
    id: "2",
    date: "13 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "3",
    date: "14 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "4",
    date: "14 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "5",
    date: "15 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "6",
    date: "16 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "7",
    date: "14 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
  {
    id: "8",
    date: "19 April 2023",
    profileImg:
      "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=300&h=300&q=80",
    profileUrl: " ",
    username: "adnan khan",
    title: "Poha",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    url: "abcd",
    category: ["Breakfast", "Dummy1", "Dummy2"],
    likedcount: "4",
    likedby: "mallesh",
    commentedBy: "asas",
    comments: "asas",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
];

export default Data;
